-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 20:37:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema manuweather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manuweather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manuweather` DEFAULT CHARACTER SET utf8 ;
USE `manuweather` ;

-- -----------------------------------------------------
-- Table `manuweather`.`atm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuweather`.`atm` (
  `id_atm` INT(11) NOT NULL AUTO_INCREMENT,
  `humidity` INT(11) NULL DEFAULT NULL,
  `pressure` FLOAT NULL DEFAULT NULL,
  `visibility` DOUBLE NULL DEFAULT NULL,
  `rising` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_atm`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manuweather`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuweather`.`country` (
  `id_country` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `cod_c_2` CHAR(2) NULL DEFAULT NULL,
  `cod_c_3` CHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manuweather`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuweather`.`state` (
  `id_state` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `abr` VARCHAR(45) NULL DEFAULT NULL,
  `size` INT(11) NULL DEFAULT NULL,
  `capital` VARCHAR(100) NULL DEFAULT NULL,
  `id_country` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_state`),
  INDEX `id_country_idx` (`id_country` ASC),
  CONSTRAINT `id_country`
    FOREIGN KEY (`id_country`)
    REFERENCES `manuweather`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manuweather`.`wind`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuweather`.`wind` (
  `id_wind` INT(11) NOT NULL AUTO_INCREMENT,
  `speed` INT(11) NULL DEFAULT NULL,
  `direction` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_wind`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `manuweather`.`days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuweather`.`days` (
  `id_day` INT NOT NULL,
  `day_name` VARCHAR(10) NULL,
  PRIMARY KEY (`id_day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manuweather`.`weather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manuweather`.`weather` (
  `id_weather` INT NOT NULL,
  `id_state` INT(11) NOT NULL,
  `date` VARCHAR(20) NULL,
  `max` INT NULL,
  `min` INT NULL,
  `temperature` INT NULL,
  `description` VARCHAR(45) NULL,
  `id_wind` INT(11) NULL DEFAULT NULL,
  `id_atm` INT(11) NULL DEFAULT NULL,
  `id_day` INT NULL,
  INDEX `id_atm` (`id_atm` ASC),
  INDEX `id_wind` (`id_wind` ASC),
  INDEX `id_day_idx` (`id_day` ASC),
  PRIMARY KEY (`id_weather`),
  CONSTRAINT `id_atm`
    FOREIGN KEY (`id_atm`)
    REFERENCES `manuweather`.`atm` (`id_atm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_wind`
    FOREIGN KEY (`id_wind`)
    REFERENCES `manuweather`.`wind` (`id_wind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_state`
    FOREIGN KEY (`id_state`)
    REFERENCES `manuweather`.`state` (`id_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_day`
    FOREIGN KEY (`id_day`)
    REFERENCES `manuweather`.`days` (`id_day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `manuweather`.`atm`
-- -----------------------------------------------------
START TRANSACTION;
USE `manuweather`;
INSERT INTO `manuweather`.`atm` (`id_atm`, `humidity`, `pressure`, `visibility`, `rising`) VALUES (1, 90, 1000, 0, 0);
INSERT INTO `manuweather`.`atm` (`id_atm`, `humidity`, `pressure`, `visibility`, `rising`) VALUES (2, 0, 10, 50, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manuweather`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `manuweather`;
INSERT INTO `manuweather`.`country` (`id_country`, `name`, `cod_c_2`, `cod_c_3`) VALUES (1, 'argentina', 'ar', 'arg');
INSERT INTO `manuweather`.`country` (`id_country`, `name`, `cod_c_2`, `cod_c_3`) VALUES (2, 'uruguay', 'ur', 'uru');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manuweather`.`state`
-- -----------------------------------------------------
START TRANSACTION;
USE `manuweather`;
INSERT INTO `manuweather`.`state` (`id_state`, `name`, `abr`, `size`, `capital`, `id_country`) VALUES (1, 'buenos aires', 'bs as', 10, 'la plata', 1);
INSERT INTO `manuweather`.`state` (`id_state`, `name`, `abr`, `size`, `capital`, `id_country`) VALUES (2, 'montevideo', 'mvd', 100, 'montevideo', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manuweather`.`wind`
-- -----------------------------------------------------
START TRANSACTION;
USE `manuweather`;
INSERT INTO `manuweather`.`wind` (`id_wind`, `speed`, `direction`) VALUES (1, 100, 12);
INSERT INTO `manuweather`.`wind` (`id_wind`, `speed`, `direction`) VALUES (2, 1, 100);

COMMIT;


-- -----------------------------------------------------
-- Data for table `manuweather`.`days`
-- -----------------------------------------------------
START TRANSACTION;
USE `manuweather`;
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (1, 'lunes');
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (2, 'martes');
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (3, 'miercoles');
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (4, 'jueves');
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (5, 'viernes');
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (6, 'sabado');
INSERT INTO `manuweather`.`days` (`id_day`, `day_name`) VALUES (7, 'domingo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `manuweather`.`weather`
-- -----------------------------------------------------
START TRANSACTION;
USE `manuweather`;
INSERT INTO `manuweather`.`weather` (`id_weather`, `id_state`, `date`, `max`, `min`, `temperature`, `description`, `id_wind`, `id_atm`, `id_day`) VALUES (DEFAULT, 1, '19/11/17', 2, -500, 36, 'pesao', 1, 1, 7);

COMMIT;

